# Generated by Django 3.1.1 on 2021-01-01 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'หน่วยงาน',
            },
        ),
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเภทหน่วยงาน',
                'verbose_name_plural': 'ประเภทหน่วยงาน',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='หัวข้อพันธกิจ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'พันธกิจ',
                'verbose_name_plural': 'พันธกิจ',
            },
        ),
        migrations.CreateModel(
            name='Strategic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='หัวข้อยุทธศาสตร์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ยุทธศาสตร์',
                'verbose_name_plural': 'ยุทธศาสตร์',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='หัวข้อกลยุทธ์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'กลยุทธ์',
                'verbose_name_plural': 'กลยุทธ์',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ปี')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ปีงบประมาณ',
                'verbose_name_plural': 'ปีงบประมาณ',
            },
        ),
        migrations.CreateModel(
            name='RmPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.CharField(blank=True, max_length=255, null=True)),
                ('strategy_other', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=999, null=True)),
                ('sign', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPService.agency', verbose_name='หน่วยงาน')),
                ('mission', models.ManyToManyField(to='UPService.Mission')),
                ('strategic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPService.strategic', verbose_name='หน่วยงาน')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPService.strategy', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'แผนบริหารจัดการความเสี่ยงและควบคุมภายใน (RM-Plan)',
                'verbose_name_plural': 'แผนบริหารจัดการความเสี่ยงและควบคุมภายใน (RM-Plan)',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.CharField(choices=[('microsoft.com', 'microsoft.com'), ('google.com', 'google.com'), ('facebook.com', 'facebook.com'), ('ปกติ', 'ปกติ')], max_length=255)),
                ('supervisor', models.BooleanField(default=False, verbose_name='หัวหน้า (ระดับหน่วยงาน)')),
                ('executive', models.BooleanField(default=False, verbose_name='หัวหน้า (ระดับมหาวิทยาลัย)')),
                ('status', models.BooleanField(default=True, verbose_name='เปิดการใช้งาน')),
                ('in_up', models.BooleanField(default=False, verbose_name='บุลคากรภายใน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPService.agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPService.agencytype'),
        ),
    ]
