# Generated by Django 3.1.1 on 2021-01-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmplan',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPService.year', verbose_name='ปีงบประมาณ'),
        ),
        migrations.AlterField(
            model_name='rmplan',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPService.agency', verbose_name='ปีงบประมาณ'),
        ),
    ]
